### ISSUE TITLE
Remove soon-to-be-duplicate functionality from protocols.forcefield._topology_molecule_to_mol2

### ISSUE THREAD

**Issue by j-wags** [openforcefield/propertyestimator#152]
@jthorton is working on integrating the functionality from https://github.com/openforcefield/propertyestimator/blob/master/propertyestimator/protocols/forcefield.py#L811-L931 back into the OpenFF Toolkit. 

So, this is a bookmark to remember to remove this soon-to-be-duplicate code when possible, just so it doesn't start to diverge.

**Comment by SimonBoothroyd** [comment]
A PR form you or @jthorton when this is moved upstream would be welcomed!

**Comment by jchodera** [comment]
Wait, why do we need `mol2` files? I thought we had collectively decided not to use them, and to standardize on SDF instead.

**Comment by jchodera** [comment]
@SimonBoothroyd : Note that you can feed SDF files to `antechamber`, which will then generate the horrible GAFF-specific `mol2` files you can feed to LEaP:
```bash
antechamber -fi mdl -i input.sdf -fo mol2 -o output.gaff.mol2
```
```

**Comment by slochower** [comment]
If you want a `mol2` without the GAFF atom types, just add `-at sybyl`.

**Comment by SimonBoothroyd** [comment]
> Wait, why do we need mol2 files? I thought we had collectively decided not to use them, and to standardize on SDF instead.

I remember hearing rumblings of this but wasn't what was decided in the end - it would be fantastic if in future decisions like this could be captured in maybe a short blog post! If this is the case I'd be happy to make the switch at some point, although looking through the issue tracker it seems like SDF support [may still be a pending feature](https://github.com/openforcefield/openforcefield/pull/281)?

(cc @j-wags)

**Comment by j-wags** [comment]
> Wait, why do we need mol2 files? I thought we had collectively decided not to use them, and to standardize on SDF instead.

The functionality for charged SDF reading/writing wasn't ready, and getting Parsley out on time was the first priority, so I made this function to get it done.

**Comment by jchodera** [comment]
We're conflating different things here. @j-wags is referring to reading/writing charged SDF files for the Open Force Field Toolkit, and I was wondering if the mol2 files were used as input to `antechamber` for GAFF parameterization. I'm still not quite sure _why_ you were using mol2 files.

In either case (OFF toolkit or antechamber/LEaP) you should not need mol2 files. I can help you get rid of them if I know why you were using them!
