### ISSUE TITLE
Including rationales, best practices, and pitfalls or open issues

### ISSUE THREAD

**Issue by mkgilson** [openforcefield/propertyestimator#28]
At the moment, it looks as though we could use a place in the organization of the docs to provide rationales for those aspects of the procedures that have specific rationales and/or are viewed as being rooted in an accepted "best practice". 

Also, I think there may be room for notes on either potential pitfalls (such as inadequate sampling of torsions in liquid-state simulations) or open issues (for example, whether to compute dielectric constants via dipole fluctuations vs applied fields.).

**Comment by mkgilson** [comment]
This issue seems to have been resolved by the property calculator call 5/2/2019.

**Comment by mkgilson** [comment]
In brief, there will be a livecoms suited document with principles of best practices etc. In the oresent protocol document, each computational component with a defined rationale will be outfitted with an item one can click to expand, which will state the rationale and provide a reference into the liveCOMS document as appropriate.

**Comment by j-wags** [comment]
Thanks for the written notes, @mkgilson. I agree with your summary, and am linking this in the [meeting notes](https://docs.google.com/document/d/16xQ8pmP6mrFP-HkFxh_3eWGrrkCukE55eOpqKSsAofY/edit#heading=h.5qvlt6ct725c)
