### ISSUE TITLE
Readthedocs is broken

### ISSUE THREAD

**Issue by jchodera** [openforcefield/propertyestimator#38]
Looks like [RTD builds](https://readthedocs.org/projects/property-estimator/builds/) have been broken for a bit:
![image](https://user-images.githubusercontent.com/3656088/58487483-f0053b00-8167-11e9-8c14-295f2caab52d.png)

**Comment by SimonBoothroyd** [comment]
This was a really frustrating one - the build only failed when creating the environment on RTD and built without issue locally. It's hard to know why exactly as RTD hides the output and errors of environment creation, but it looks like this should be fixed by #39.

**Comment by SimonBoothroyd** [comment]
Confirmed this fixes the issue: https://readthedocs.org/projects/property-estimator/builds/9138954/
