### ISSUE TITLE
Standard release process

### ISSUE THREAD

**Issue by j-wags** [openforcefield/propertyestimator#76]
### 1: Update the release history documentation file, using this template
 
```
# 0.2.2

This release modifies an example to show how to parameterize a solvated system, cleans up backend code, and makes several improvements to the README.

A richer version of these release notes with live links to API documentation is available on [our ReadTheDocs page](https://open-forcefield-toolkit.readthedocs.io/en/latest/releasehistory.html)

See our [installation instructions](https://open-forcefield-toolkit.readthedocs.io/en/latest/installation.html).

Please report bugs, request features, or ask questions through our [issue tracker](https://github.com/openforcefield/openforcefield/issues).

**Please note that there may still be some changes to the API prior to a stable 1.0.0 release.**

### Bugfixes

* PR #279: Cleanup of unused code/warnings in main package __init__
* PR #259: Update T4 Lysozyme + toluene example to show how to set up solvated systems
* PR #256 and PR #274: Add functionality to ensure that links in READMEs resolve successfully
```

Merge the above release summary into the release history file in a PR.

### 2: Cut the release on GitHub

* Go to the `Releases` tab on the front page of the repo
* Draft a new release
```
#### Tag = `X.Y.Z` @ master

#### Title = `X.Y.Z [Descriptive Title]`
```

Copy the text from the release summary in part 1), being sure to convert to MarkDown if necessary. 

You do NOT need to upload any files. The source code will automatically be added as a tar.gz.

And check ` This is a pre-release`

### 3: Trigger a new build on Omnia. 

Note: Omnia builds take about 30 minutes to run. When you open a PR, the build will run, and you can check the bottom of the travis logs for "package failed to build" listings. Some packages always fail (protons, assaytools), but propertyestimator shouldn't be there. Ctrl-F for `propertyestimator` to ensure that it did build at all, though. 

* Create branch or fork of omnia-md/conda-recipes with changes to propertyestimator in [meta.yaml](https://github.com/omnia-md/conda-recipes/blob/master/propertyestimator/meta.yaml):
  * git_tag set to match git release (This tag can also be a branch name)
  * version set to match git release (this will go into the conda package name)
  * build set to 0
  * any updated dependencies reflected under requirements:
  * If we want to push to special `rc` label: use extra.upload
* Open PR to merge branch or fork into omnia-md master
  * PR should be called, eg `[propertyestimator] 0.0.1 (label: rc)`
  * No PR body text is needed
  * Travis will run on this PR (~30 minutes) and attempt to build the package. Under no conditions will the package built before the PR is merged be uploaded. This step is just to ensure that building doesn't crash. 
  * If build is successful, PR should be reviewed and merged by omnia maintainers
  * **Once merged into master** Package is built again on travis, and pushed to the channel set in meta.yaml (main,beta, or rc)
  * If we have `upload: rc`, we would install with `conda install -c omnia/label/rc propertyestimator`
* Test omnia package
  * `conda install -c omnia/label/rc openforcefield`

### 4: Update the ReadTheDocs build versions
* Trigger RTD build of latest (we need to do this to make RTD aware of the new tagged release)
* Under `Versions` tab, add new release version to list of built versions and SAVE
* Verify new version docs have built and pushed correctly
* Under `Admin` | `Advanced Settings`: Set new release version as Default version to display and SAVE

### 5: Announce the release
Post something like this in #general 
```
@channel We're pleased to announce the release of the Open Force Field Toolkit version 0.4.0! This release introduces updates to the SMIRNOFF spec, the ability to read SMIRNOFF 0.1 spec OFFXML files, and performance improvements for system creation. Detailed release notes are available at https://open-forcefield-toolkit.readthedocs.io/en/0.4.0/releasehistory.html

Conda packages available now on the `omnia` channel for both Linux and MacOS!
https://anaconda.org/omnia/openforcefield/files
```

**Comment by SimonBoothroyd** [comment]
Closing as this is now integrated into the developer docs.
